<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'PhabricatorGitlabAuthProvider' => 'src/oauth/PhabricatorGitlabAuthProvider.php',
    'PhutilGitlabAuthAdapter' => 'src/oauth/PhutilGitlabAuthAdapter.php',
  ),
  'function' => array(),
  'xmap' => array(
    'PhabricatorGitlabAuthProvider' => 'PhabricatorOAuth2AuthProvider',
    'PhutilGitlabAuthAdapter' => 'PhutilOAuthAuthAdapter',
  ),
));
